# NumPy


In [301]:
%pip install numpy

import numpy as np
print(np.__version__)

arr = np.array([1,2,3,4])
print(arr)
print(type(arr))

arr_from_tuple = np.array(('a', 'b', 'c'))
print(arr_from_tuple)
print(type(arr_from_tuple))

Note: you may need to restart the kernel to use updated packages.
2.2.6
[1 2 3 4]
<class 'numpy.ndarray'>
['a' 'b' 'c']
<class 'numpy.ndarray'>


## Array Dimensions

In [302]:

# -------------------------
# 0D array (Scalar)
# -------------------------
# A single value with no dimensions
arr_0d = np.array(10)
print(arr_0d)
print("Dimensions:", arr_0d.ndim)

# -------------------------
# 1D array (Vector)
# -------------------------
# A classic one-dimensional array made of scalar values
arr_1d = np.array([1, 2, 3, 4])
print(arr_1d)
print("Dimensions:", arr_1d.ndim)

# -------------------------
# 2D array (Matrix)
# -------------------------
# An array made of 1D arrays (rows and columns)
arr_2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(arr_2d)
print("Dimensions:", arr_2d.ndim)

# -------------------------
# 3D array (Tensor)
# -------------------------
# An array made of 2D arrays
arr_3d = np.array([
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ],
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ]
])
print(arr_3d)
print("Dimensions:", arr_3d.ndim)

# -------------------------
# Higher-dimensional array
# -------------------------
# Force a minimum of 10 dimensions
more_dimensions = np.array([1, 2, 3], ndmin=10)
print(more_dimensions)
print("Dimensions:", more_dimensions.ndim)




10
Dimensions: 0
[1 2 3 4]
Dimensions: 1
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Dimensions: 2
[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
Dimensions: 3
[[[[[[[[[[1 2 3]]]]]]]]]]
Dimensions: 10


## Building arrays

In [303]:

# -------------------------
# full(shape, value)
# -------------------------
# Create an array filled with a specific value
arr_full = np.full((3, 2, 1), 'x')
print(arr_full)

# -------------------------
# zeros(shape)
# -------------------------
# Create an array filled with zeros
arr_zeros = np.zeros((3, 3, 3))
print(arr_zeros)

# -------------------------
# ones(shape)
# -------------------------
# Create an array filled with ones
arr_ones = np.ones((3, 3))
print(arr_ones)

# -------------------------
# arange(start, stop, step)
# -------------------------
# Create values from start to stop (exclusive) using a step size
arr_arange = np.arange(10, 100, 10)
print(arr_arange)

# -------------------------
# linspace(start, stop, num)
# -------------------------
# Create evenly spaced values between two numbers (inclusive)
arr_linspace = np.linspace(20, 50, 6)
print(arr_linspace)

# -------------------------
# empty(shape) + fill(value)
# -------------------------
# Create an uninitialized array, then fill it
arr_empty = np.empty((5, 5))
arr_empty.fill(1)
print(arr_empty)



[[['x']
  ['x']]

 [['x']
  ['x']]

 [['x']
  ['x']]]
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[10 20 30 40 50 60 70 80 90]
[20. 26. 32. 38. 44. 50.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


## Looking at the Shape of an Array

NumPy arrays have a shape, which describes the number of dimensions and the size of each dimension.

In [304]:
#Shape
arr = np.array([[
  [1,2,3],
  [4,5,6],
  [7,8,9]
],[
  [1,2,3],
  [4,5,6],
  [7,8,9]
]] )
print(arr.shape)

(2, 3, 3)


(2, 3, 3) → 2 layers, each with 3 rows and 3 columns

In other words:
- There are 2 two-dimensional arrays
- Each 2D array contains 3 one-dimensional arrays (rows)
- Each 1D array contains 3 zero-dimensional values (scalars)

In [305]:

# -------------------------
# Reshape
# -------------------------
# Reshaping changes the shape of an array WITHOUT changing its data.
# The total number of elements must stay the same.
#
# Examples:
# 3 × 3 = 9 elements
# 3 × 1 × 3 = 9 elements
# 9 × 1 = 9 elements

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
reshaped_1 = arr.reshape(3, 3)
print(reshaped_1)

# -------------------------
# More reshape examples
# -------------------------
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

reshaped_2 = arr.reshape(2, 3, 2)
reshaped_3 = arr.reshape(4, 3)

print(reshaped_2)
print(reshaped_3)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


## Your Turn

Create a NumPy array containing 10 elements. Practice reshaping it into as many different valid shapes as possible.


## Array indexing 

In [306]:
arr = np.array([
    [
        [1, 2, 3],
        [4, 5, 6],
    ],
    [
        [7, 8, 9],
        [10, 11, 12],
    ],
])

# First 2D array
print(arr[0])

# First row of the first 2D array
print(arr[0][0])

# First element of the first row
print(arr[0][0][0])

# First 2D array, second row
print(arr[0, 1])

# Second 2D array, second row, second element
print(arr[1, 1, 1])


[[1 2 3]
 [4 5 6]]
[1 2 3]
1
[4 5 6]
11


## Slicing

In [322]:
# Slicing syntax
# [start : end : step]

arr = np.array([1, 2, 3, 4, 5, 6])

# First three elements
print(arr[:3])

# From index 3 to the end
print(arr[3:])

# Every other element
print(arr[::2])

# Every other element, starting at index 1
print(arr[1::2])

# Slice using negative indices
print(arr[-4:-2])




[1 2 3]
[4 5 6]
[1 3 5]
[2 4 6]
[3 4]


In [ ]:
# Slicing 2d arrays
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
])

# Second row, first two columns
print(arr[1, :2])

# First two rows, columns starting from index 1
print(arr[:2, 1:])

[4 5]
[[2 3]
 [5 6]]


## Your turn: 
Slice this from the array below this
 [[ 1,  3],
  [ 7,  9]]

In [ ]:
arr = np.array([
    [
        [1, 2, 3],
        [4, 5, 6],
    ],
    [
        [7, 8, 9],
        [10, 11, 12],
    ],
])

# All arrays, first row, every other element
print(arr[:, 0, ::2])

[[1 3]
 [7 9]]


# Looping through arrays
NumPy has tools that reduce the need for loops, but let’s take a look at how this works in vanilla Python.

In [ ]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
])

for i in arr:
    print("axis 0:", i)

for i in arr:
    for j in i:
        print(j)


ax 0 [1 2 3]
ax 0 [4 5 6]
ax 0 [7 8 9]
ax 0 [1 2 3]
ax 0 [4 5 6]
ax 0 [7 8 9]
1
2
3
4
5
6
7
8
9
1
2
3
4
5
6
7
8
9


Lets make it easier

In [ ]:
# nditer
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
])

# Iterate over every element in the 2D array
for i in np.nditer(arr):
    print(i)

arr = np.array([
    [
        [1, 2],
        [3, 4],
    ],
    [
        [5, 6],
        [7, 8],
    ],
])

# Iterate over every element in the 3D array
for x in np.nditer(arr):
    print(x)


1
2
3
4
5
6
7
8
9
1
2
3
4
5
6
7
8
9
1
2
3
4
5
6
7
8


In [ ]:
arr = np.array([
    [1,  2,  3,  4,  5],
    [6,  7,  8,  9, 10],
    [11, 12, 13, 14, 15],
])

# For every row, slice columns 1 through 3
for value in np.nditer(arr[:, 1:4]):
    print(value)



2
3
4
7
8
9
12
13
14


## Joining Arrays


In [ ]:
# Join
# SQL joins are based on keys. In NumPy, joins are based on axes.

nums1 = np.array([1, 2, 3])
nums2 = np.array([1, 2, 3])

all_nums = np.concatenate((nums1, nums2))
print(all_nums)

[1 2 3 1 2 3]


In [ ]:
nums1_2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
])

nums2_2d = np.array([
    [5, 6, 7],
    [8, 9, 10],
])

all_nums_ax0 = np.concatenate((nums1_2d, nums2_2d), axis=0)
all_nums_ax1 = np.concatenate((nums1_2d, nums2_2d), axis=1)

print(all_nums_ax0)
print(all_nums_ax1)


[[ 1  2  3]
 [ 4  5  6]
 [ 5  6  7]
 [ 8  9 10]]
[[ 1  2  3  5  6  7]
 [ 4  5  6  8  9 10]]


In [ ]:
nums1_2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
])

nums2_2d = np.array([
    [5, 6, 7],
    [8, 9, 10],
])

# Stacks
# Adds a new axis
stack = np.stack((nums1_2d, nums2_2d))
print(stack)

# Joins arrays vertically (axis 0)
vstack = np.vstack((nums1_2d, nums2_2d))
print(vstack)

# Joins arrays side by side (axis 1)
hstack = np.hstack((nums1_2d, nums2_2d))
print(hstack)


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 5  6  7]
  [ 8  9 10]]]
[[ 1  2  3]
 [ 4  5  6]
 [ 5  6  7]
 [ 8  9 10]]
[[ 1  2  3  5  6  7]
 [ 4  5  6  8  9 10]]


## Splitting arrays

In [ ]:
# Splitting Arrays

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
split_array = np.array_split(arr, 4)
print(split_array)

arr_2d = np.array([
    [1,  2,  3,  4],
    [5,  6,  7,  8],
    [9, 10, 11, 12],
])

split_array_2d = np.array_split(arr_2d, 2, axis=1)
print(split_array_2d)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]), array([10, 11, 12])]
[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12]])]


## Where 
Who needs loops when you have where

In [ ]:
# Where
arr = np.array([0.42, 0.87, 0.13, 0.66, 0.91, 0.05, 0.74, 0.38, 0.59, 0.21])
search = np.where(arr < 0.5)
print(search)

# Sort
sorted_arr = np.sort(arr)
print(sorted_arr)

arr = np.array(["Ix", "Eric", "Rose"])
print(np.sort(arr))

arr_2d = np.array([
    [3, 1, 4, 2],
    [7, 5, 8, 6],
    [11, 9, 12, 10],
])

sorted_2d = np.sort(arr_2d)
print(sorted_2d)


(array([0, 2, 5, 7, 9]),)
[0.05 0.13 0.21 0.38 0.42 0.59 0.66 0.74 0.87 0.91]
['Eric' 'Ix' 'Rose']
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


## Your Turn

Given the array below, use np.where() to find the indices of all values that are between 0.3 and 0.7 (inclusive).
arr = np.array([0.15, 0.32, 0.58, 0.71, 0.44, 0.89, 0.67])
Hint you can use the '&' operator 


In [ ]:
result = np.where((arr >= 0.3) & (arr <= 0.7))
print(result)

print(arr[result])

## Comparing 

In [ ]:

arr1 = np.array([
    [2., 5., 1.],
    [8., 3., 4.],
])

arr2 = np.array([
    [3., 2., 1.],
    [6., 5., 10.],
])

print(arr1 < arr2)


[[ True False False]
 [False  True  True]]


## Boolean Indexing
Boolean indexing can simplify data for ML models.

In [ ]:
arr = np.array(["Ix", "Eric", "Rose"])

data = np.random.randint(2, size=(3, 4))

print(data[arr == "Ix"])
print(data)


[[1 1 0 1]]
[[1 1 0 1]
 [0 0 1 1]
 [1 1 0 0]]


## Conditions 


In [ ]:
scores = np.array([0.85, 0.42, 0.90, 0.67, 0.30])
cond = scores > 0.5

print(cond)

[ True False  True  True False]


## Your Turn

Given the array below, create a boolean condition that checks which values are greater than or equal to 75.
scores = np.array([92, 68, 81, 74, 59, 88, 77])


In [ ]:
scores = np.array([92, 68, 81, 74, 59, 88, 77])

con = scores >= 75
print(con)

## Math
- mean
- sum - total
- cumsum - sum as we go

In [336]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr.mean())
print(arr.sum())
print(arr.cumsum())

5.5
55
[ 1  3  6 10 15 21 28 36 45 55]


AI Transparency Statement:
AI tools were used to assist with cleaning up formatting and improving grammar. All instructional content, examples, and technical decisions were created by the instructor.